SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE PROCEDURE RAISE_SALARY_BY_PCT(
  P_DEPTNO IN NUMBER,
  P_PERCENT IN NUMBER
)
IS
BEGIN
  UPDATE EMP
  SET BASIC_SAL = BASIC_SAL + (BASIC_SAL * P_PERCENT / 100)
  WHERE DEPTNO = P_DEPTNO;

  DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' employee(s) updated.');
  COMMIT;
END;
/

ACCEPT p_deptno NUMBER PROMPT 'Enter department number: '
ACCEPT p_percent NUMBER PROMPT 'Enter increase percentage: '

BEGIN
  RAISE_SALARY_BY_PCT(&p_deptno,&p_percent);
END;
/
