SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE PROCEDURE SEARCH_EMP(
  P_EID IN NUMBER,
  P_NAME OUT VARCHAR2
)
IS
BEGIN
  SELECT ENAME INTO P_NAME
  FROM EMP
  WHERE EID = P_EID;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    P_NAME := NULL;
    RAISE_APPLICATION_ERROR(-20001,'Employee not found.');
END;
/

ACCEPT p_eid NUMBER PROMPT 'Enter EID: '

DECLARE
  v_name VARCHAR2(100);
BEGIN
  SEARCH_EMP(&p_eid,v_name);
  DBMS_OUTPUT.PUT_LINE('Employee Name = ' || v_name);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/
