SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE FUNCTION SQUARE_NUM(P_NUM IN NUMBER)
RETURN NUMBER
IS
BEGIN
  RETURN P_NUM * P_NUM;
END;
/

ACCEPT p_num NUMBER PROMPT 'Enter number: '

BEGIN
  DBMS_OUTPUT.PUT_LINE('Square = ' || SQUARE_NUM(&p_num));
END;
/

PROMPT To call on SQL*Plus command line:
PROMPT SELECT SQUARE_NUM(5) FROM DUAL;
