SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE FUNCTION GET_BALANCE(P_ACNO IN NUMBER)
RETURN NUMBER
IS
  V_BALANCE ACCOUNT.BALANCE%TYPE;
BEGIN
  SELECT BALANCE INTO V_BALANCE
  FROM ACCOUNT
  WHERE ACNO = P_ACNO;

  RETURN V_BALANCE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20002,'Account not found.');
END;
/

ACCEPT p_acno NUMBER PROMPT 'Enter account number: '

BEGIN
  DBMS_OUTPUT.PUT_LINE('Balance = Rs. ' || GET_BALANCE(&p_acno));
END;
/
