SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE UPDATE_EMP_VALUES
IS
BEGIN
  UPDATE EMP
  SET BASIC_SAL = BASIC_SAL + 1000;
  DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' employee(s) updated.');
  COMMIT;
END;
/

BEGIN
  UPDATE_EMP_VALUES;
END;
/
