SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE PROCEDURE RAISE_SALARY_BY_AMOUNT(
  P_DEPTNO IN NUMBER,
  P_AMOUNT IN NUMBER
)
IS
BEGIN
  UPDATE EMP
  SET BASIC_SAL = BASIC_SAL + P_AMOUNT
  WHERE DEPTNO = P_DEPTNO;

  DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' employee(s) updated.');
  COMMIT;
END;
/

ACCEPT p_deptno NUMBER PROMPT 'Enter department number: '
ACCEPT p_amount NUMBER PROMPT 'Enter salary increase amount: '

BEGIN
  RAISE_SALARY_BY_AMOUNT(&p_deptno,&p_amount);
END;
/
