SET SERVEROUTPUT ON

CREATE OR REPLACE FUNCTION SQUARE_NUM_2(P_NUM IN NUMBER)
RETURN NUMBER
IS
BEGIN
  RETURN P_NUM * P_NUM;
END;
/

ACCEPT p_num NUMBER PROMPT 'Enter number: '

BEGIN
  DBMS_OUTPUT.PUT_LINE('Square = ' || SQUARE_NUM_2(&p_num));
END;
/

PROMPT Command-line SQL example:
PROMPT SELECT SQUARE_NUM_2(7) FROM DUAL;
