SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT p_eid NUMBER PROMPT 'Enter EID: '

DECLARE
  v_name EMP.ENAME%TYPE;
BEGIN
  SELECT ENAME INTO v_name FROM EMP WHERE EID = &p_eid;
  DBMS_OUTPUT.PUT_LINE('Employee Name = ' || v_name);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO_DATA_FOUND: No employee exists with EID ' || &p_eid);
END;
/
