SET SERVEROUTPUT ON

DECLARE
  v_num NUMBER;
BEGIN
  v_num := 10 / 0;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SQLCODE = ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM = ' || SQLERRM);
END;
/
