SET SERVEROUTPUT ON

DECLARE
  CURSOR c_emp IS
    SELECT EID, ENAME, BASIC_SAL
    FROM EMP
    ORDER BY BASIC_SAL DESC;
BEGIN
  FOR r IN c_emp LOOP
    DBMS_OUTPUT.PUT_LINE(r.EID || ' | ' || r.ENAME || ' | ' || r.BASIC_SAL);
  END LOOP;
END;
/
